import mongoose, { Schema, Document } from "mongoose";

export interface IPartyPlan extends Document {
  userId: mongoose.Types.ObjectId;
  clerkId: string;
  type: "PARTY" | "SOLO" | "RECOVERY";
  data: any; // Storing the raw JSON payload generated by the AI
  createdAt: Date;
  updatedAt: Date;
}

const PartyPlanSchema: Schema = new Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
    clerkId: { type: String, required: true },
    type: { type: String, enum: ["PARTY", "SOLO", "RECOVERY"], required: true },
    data: { type: Schema.Types.Mixed, required: true },
  },
  { timestamps: true }
);

const PartyPlan = mongoose.models.PartyPlan || mongoose.model<IPartyPlan>("PartyPlan", PartyPlanSchema);

export default PartyPlan;
